### ISSUE TITLE
allow per call override of the timeout baked into the Client

### ISSUE THREAD

**Issue by marc-portier** [brianhealey/pyamplipi#13]
The HTTP-POST call to `/announce` waits for the actual mp3 to be played before the HTTP response is returned.
For (not even that) lengthy announcements this easily conflicts with [the standard 10s timeout](https://github.com/brianhealey/pyamplipi/blob/main/pyamplipi/amplipi.py#L15) baked into the [`pyampli.client.Client`](https://github.com/brianhealey/pyamplipi/blob/main/pyamplipi/client.py#L23)

As things are one either needs to: 
* set up a client with an unreasonably high timeout to be useful for any lengthy announcement
* make a separate client with a high enough timeout for the announcement (creating its own session)

Both options have their drawbacks which could be overcome by 
1. allow to pass a `timeout=«custom for this call only»` into the [`pyamplipi.ampllipi.Amplipi.announce()`](https://github.com/brianhealey/pyamplipi/blob/main/pyamplipi/amplipi.py#L121) 
2. further pass that down into [`pyamplipi.client.Client.post()`](https://github.com/brianhealey/pyamplipi/blob/main/pyamplipi/client.py#L146)
3. and there use that timeout (if provided) on a single-call basis to override the timeout baked into the client (and used for all other calls)

If this sounds like a reasonable approach, I can provide the PR
While at it we might consider having this kind of call-basis-override possibility for other functions too?
(Although I do not know if any other calls have a similar lengthy wait for the response?) 

Finally. Note that there is somewhat of an opportunity for @micro-nova to reconsider this synchronous wait behavior for the `/announce` service: 
Another approach, with a more web-like prompt response, would be to have an immediate response using an [`202 Accepted`](https://www.rfc-editor.org/rfc/rfc2616#section-10.2.3) - possibly accompanied with a `Location:`  pointing to a resource that reports on the progress and eventual completion of the announcement being played.  This however is outside the realm of this python client-library.

**Comment by linknum23** [comment]
I added an issue so that we can fix this for real in the future, however this will require some re-architecting so it will take some time.

In the meantime I think adding a special case for the announcement makes sense, To make this easy to use  one options would be to have the announcement's  timeout default to something like 10 or 15 seconds. Another would be to fail with a useful message to set/increase the timeout.
