### ISSUE TITLE
Stop not implemented

### ISSUE THREAD

**Issue by hawkeyeP** [brianhealey/pyamplipi#3]
Stop should be implemented just like pause.

[pyamplipi](https://github.com/brianhealey/pyamplipi)/pyamplipi/amplipi.py

```
    async def stop_stream(self, stream_id: int) -> Stream:
        response = await self._client.post(f'streams/{stream_id}/stop')
        return Stream.parse_obj(response)
```

**Comment by brianhealey** [comment]
It should be implemented in 0.4.8. Let me know if you have any issues.

**Comment by hawkeyeP** [comment]
Stop appears to be working, thank you!
The source on the input media_players can only be changed from an rca input to a stream, but not from a stream back to the rca input.  In the HA developer tools the 'source' attribute for the input remains on the rca input and never changes to the stream name.

**Comment by brianhealey** [comment]
Would you mind trying it now? I refactored the source, and source_list logic to allow for 'None' and it might have cleared this issue up.
