### ISSUE TITLE
install dependencies should get listed in the setup.py

### ISSUE THREAD

**Issue by marc-portier** [brianhealey/pyamplipi#6]
after `pip install pyamplipi` one can not just start using the library without also including its dependencies: 

even a simple `from pyamplipi.amplipi import AmpliPi` yields an error (in that case: missing dependency aiohttp)

most straightforward approach would be to have the setup.py take over the dependencies from the requirements.txt file (or using a tool like poetry to handle it)

**Comment by linknum23** [comment]
I can easily add this as a PR if it helps.

**Comment by marc-portier** [comment]
Quickly jotting down some boilerplate code to be added to `setup.py` to handle this

```python
def required(sfx=''):
    """ Load the requirements from the requirements.txt file"""
    reqs = []
    try:
        with open(f"requirements{sfx}.txt") as f:
            reqs = [ln.strip() for ln in f.readlines() if not ln.startswith('-') and not ln.startswith('#') and ln.strip() != '']
    finally:
        return reqs

requirements = required()
requirements_dev = required('-dev')

setup ( 
    name = 'pyamplipi', 
    ....,
    install_requires=requirements,
    extras_require={'dev' : requirements_dev}, 
    ....
)
```

With this:
- people can do a local pip install from source with `pip install -e . `
- people can be assured that while installing this lib all its dependencies (as mentioned in `requirements.txt`) will be installed as well

Note: 
It also allows for separated dependencies during development (like stuff needed for tests, doc generating....) --> through `pip install -e .[dev]`

I would be cracking up a PR along these lines one of these days.

Unless people prefer the road via [poetry](https://python-poetry.org/) which is more impactful on the code base, but arguably even more feature-complete yet easier/more elegant to manage (as all of that is deferred to the external tool)

**Comment by marc-portier** [comment]
kind request to reopen -- since the applied merge is now missing the `return reqs` as mentioned in the comments on the PR #10
